AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 
  Resume Challenge backend stack
Globals:
  Api:
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tsresumefe

  VisitorCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: dynamo_helper.lambda_handler
      Runtime: python3.8
      Policies: AmazonDynamoDBFullAccess
      Events:
        VisitorUpdate:
          Type: Api
          Properties:
            Path: /visitor_count
            Method: get
  
  VisitorCountTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions:
      - AttributeName: 'VisitorCount'
        AttributeType: 'N'
      KeySchema:
      - AttributeName: 'VisitorCount'
        KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST
      TableName: Visitors
